# Generated by Django 4.2.30 on 2026-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image_url',
            field=models.URLField(blank=True, max_length=5000000000000, null=True),
        ),
    ]
