# Generated by Django 4.2.30 on 2026-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0002_alter_products_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
