# Generated by Django 4.2.30 on 2026-09-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0003_products_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
