# Generated by Django 4.2.30 on 2026-09-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0004_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=150)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_u_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='krishnaTyreApiApp.user')),
                ('service_center', models.ForeignKey(db_column='service_center_u_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_center_appointments', to='krishnaTyreApiApp.user')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
