# Generated by Django 4.2.30 on 2026-09-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0005_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAppointments',
            fields=[
                ('emergency_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=500)),
                ('issue_photo_urls', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_u_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_emergency_appointments', to='krishnaTyreApiApp.user')),
                ('service_center', models.ForeignKey(db_column='service_center_u_id', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_service_center_appointments', to='krishnaTyreApiApp.user')),
            ],
            options={
                'db_table': 'emergency_appointments',
            },
        ),
    ]
