# Generated by Django 4.2.30 on 2026-09-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0006_emergencyappointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_u_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_bills', to='krishnaTyreApiApp.user')),
                ('owner', models.ForeignKey(db_column='owner_u_id', on_delete=django.db.models.deletion.CASCADE, related_name='generated_bills', to='krishnaTyreApiApp.user')),
            ],
            options={
                'db_table': 'generated_bills',
            },
        ),
    ]
