# Generated by Django 4.2.30 on 2026-09-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0007_generatedbills'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBillServices',
            fields=[
                ('bill_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='krishnaTyreApiApp.generatedbills')),
            ],
            options={
                'db_table': 'generated_bill_services',
            },
        ),
    ]
