# Generated by Django 4.2.30 on 2026-09-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0008_generatedbillservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyappointments',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
