# Generated by Django 4.2.30 on 2026-09-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0009_emergencyappointments_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyappointments',
            name='is_available',
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_service',
            field=models.BooleanField(default=False, help_text='Whether this owner offers 24/7 emergency roadside service.'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_open',
            field=models.BooleanField(default=True, help_text='Whether the shop is currently open and accepting bookings.'),
        ),
    ]
