# Generated by Django 4.2.30 on 2026-09-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop_owner',
            new_name='owner',
        ),
    ]
