# Generated by Django 4.2.30 on 2026-09-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0014_remove_user_groups_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('kyc_id', models.AutoField(primary_key=True, serialize=False)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='pending', help_text='pending | verified | rejected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='krishnaTyreApiApp.user')),
            ],
            options={
                'db_table': 'kyc',
                'indexes': [models.Index(fields=['u_id'], name='kyc_u_id_9610ce_idx'), models.Index(fields=['status'], name='kyc_status_a392b6_idx')],
            },
        ),
    ]
