# Generated by Django 4.2.30 on 2026-09-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishnaTyreApiApp', '0015_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_id', models.CharField(choices=[('bike_3m', 'Bike - Quarterly'), ('bike_6m', 'Bike - Half Yearly'), ('bike_1y', 'Bike - Yearly'), ('auto_3m', 'Auto - Quarterly'), ('auto_6m', 'Auto - Half Yearly'), ('auto_1y', 'Auto - Yearly'), ('car_3m', 'Car - Quarterly'), ('car_6m', 'Car - Half Yearly'), ('car_1y', 'Car - Yearly'), ('van_3m', 'Van - Quarterly'), ('van_6m', 'Van - Half Yearly'), ('van_1y', 'Van - Yearly'), ('truck_3m', 'Truck - Quarterly'), ('truck_6m', 'Truck - Half Yearly'), ('truck_1y', 'Truck - Yearly'), ('container_3m', 'Container - Quarterly'), ('container_6m', 'Container - Half Yearly'), ('container_1y', 'Container - Yearly')], help_text='Plan identifier (e.g. car_6m)', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto / 3-Wheeler'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('container', 'Container Truck')], help_text='Vehicle category', max_length=20)),
                ('plan_title', models.CharField(help_text='Display name (Quarterly / Half Yearly / Yearly)', max_length=50)),
                ('amount_paise', models.IntegerField(help_text='Amount in paise (e.g. 109900 = ₹1099)')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('duration_days', models.IntegerField(help_text='Plan duration in days')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(default='razorpay', help_text='razorpay | manual | upi', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='Set when subscription becomes active', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Calculated from started_at + duration_days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='krishnaTyreApiApp.user')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['u_id', 'status'], name='subscriptio_u_id_fb4134_idx'), models.Index(fields=['status', 'expires_at'], name='subscriptio_status_b3f3e1_idx')],
            },
        ),
    ]
